### ISSUE TITLE
Error when executing ControlPanel in Scilabs 5.5.2 (Windows XP)

### ISSUE THREAD

**Issue by obstri** [craftweeks/MDX-LabPanel#12]
Hello,

I am running SciLabs v.5.5.2 and trying to execute MDX labpanel v.0.4 on a Windows XP computer

I am getting an error which is saying:

Undefined variable: updateAxisXY
at line 597 of exec file called by:
c);  disp(msprintf(gettext(
while executing a callback

Do you have any solves to this issue?

Thanks in advance.

**Comment by chriskyfung** [comment]
Hi @obstri,

Thank you for reporting this issue. Unfortunately, we don't have a Windows XP computer for testing, so we can't replicate the problem directly. However, here are a few suggestions that might help you resolve the issue:

1. **Update to Latest Release**: Please download and try running the latest release, `v0.4.1`, instead of the pre-release `v0.4`.
2. **Correct File Extraction**: Ensure that you have correctly cloned the repository or unzipped the release file so that all project files are located in the same directory.
3. **Proper GUI Initialization**: Start the GUI by using the `__main__.sce` file to ensure that both `commands.sce` (backend) and `ControlPanel.sce` (frontend) are executed simultaneously in Scilab.
4. **Verify File Locations**: Cross-check the relative paths defined within the scripts to ensure that all files are correctly located.

Please let us know if any of these suggestions help or if you need further assistance.

Thanks again for your patience and understanding.
